<a href="https://colab.research.google.com/github/ValerieGrimault/Coherence_des_donnees/blob/master/BON.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
!pip install -r https://raw.githubusercontent.com/datamllab/automl-in-action-notebooks/master/requirements.txt

In [ ]:
pip install autokeras

  Using cached autokeras-1.0.16.post1-py3-none-any.whl (166 kB)
  Using cached tensorflow-2.5.2-cp39-cp39-win_amd64.whl (422.7 MB)
  Using cached keras_tuner-1.0.4-py3-none-any.whl (97 kB)
  Using cached kt_legacy-1.0.4-py3-none-any.whl (9.6 kB)
  Using cached tensorboard-2.7.0-py3-none-any.whl (5.8 MB)
  Using cached grpcio-1.34.1-cp39-cp39-win_amd64.whl (2.9 MB)
  Using cached flatbuffers-1.12-py2.py3-none-any.whl (15 kB)
  Using cached google_pasta-0.2.0-py3-none-any.whl (57 kB)
  Using cached protobuf-3.19.1-cp39-cp39-win_amd64.whl (895 kB)
  Using cached opt_einsum-3.3.0-py3-none-any.whl (65 kB)
  Using cached six-1.15.0-py2.py3-none-any.whl (10 kB)
  Using cached gast-0.4.0-py3-none-any.whl (9.8 kB)
  Using cached astunparse-1.6.3-py2.py3-none-any.whl (12 kB)
  Using cached Keras_Preprocessing-1.1.2-py2.py3-none-any.whl (42 kB)
  Using cached absl_py-0.15.0-py3-none-any.whl (132 kB)
  Using cached h5py-3.1.0-cp39-cp39-win_amd64.whl (2.7 MB)
  Using cached termcolor-1.1.0-py3-none

ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
daal4py 2021.3.0 requires daal==2021.2.3, which is not installed.
conda-repo-cli 1.0.4 requires pathlib, which is not installed.
cookiecutter 1.7.2 requires Jinja2<3.0.0, but you have jinja2 3.0.2 which is incompatible.
cookiecutter 1.7.2 requires MarkupSafe<2.0.0, but you have markupsafe 2.0.1 which is incompatible.
bokeh 2.4.1 requires typing-extensions>=3.10.0, but you have typing-extensions 3.7.4.3 which is incompatible.


## Titanic data downloaded with csv files

### Download training and testing csv files

In [ ]:
import tensorflow as tf
TRAIN_DATA_URL = "https://storage.googleapis.com/tf-datasets/titanic/train.csv"
TEST_DATA_URL = "https://storage.googleapis.com/tf-datasets/titanic/eval.csv"
 
train_file_path = tf.keras.utils.get_file("train.csv", TRAIN_DATA_URL)
test_file_path = tf.keras.utils.get_file("eval.csv", TEST_DATA_URL)

### Run `StructuredDataClassifier` API

In [ ]:
# Initialize the structured data classifier.
clf = ak.StructuredDataClassifier(max_trials=1) # Try 10 different pipelines.

# Feed the structured data classifier with training data.
clf.fit(
    # The path to the train.csv file.
    train_file_path,
    # The name of the label column.
    'survived',
    verbose=2,)

INFO:tensorflow:Reloading Oracle from existing project .\structured_data_classifier\oracle.json
INFO:tensorflow:Reloading Tuner from .\structured_data_classifier\tuner0.json


KeyError: 'structured_data_block_2/normalize'

In [ ]:
import autokeras as ak
clf = ak.StructuredDataClassifier(
    column_names=[
        'sex',
        'age',
        'n_siblings_spouses',
        'parch',
        'fare',
        'class',
        'deck',
        'embark_town',
        'alone'],
    column_types={'sex': 'categorical',
                  'fare': 'numerical'},
    max_trials=2,
)

clf.fit(
    train_file_path,
    'survived',
    verbose=2,)

INFO:tensorflow:Reloading Oracle from existing project .\structured_data_classifier\oracle.json
INFO:tensorflow:Reloading Tuner from .\structured_data_classifier\tuner0.json


KeyError: 'structured_data_block_2/normalize'

### Predict with the best model.

In [ ]:
predicted_y = clf.predict(test_file_path)
print(predicted_y[:5])

### Evaluate the best pipeline with the testing csv file.

In [ ]:
test_loss, test_acc = clf.evaluate(test_file_path, 'survived', verbose=0)
print('Test accuracy: ', test_acc)

In [ ]:
best_model = clf.export_model()
best_model.summary()

In [ ]:
 tf.keras.utils.plot_model(best_model, show_shapes=True, expand_nested=True)

In [ ]:
test_file_path = test_file_path.astype('string')

In [ ]:
import pandas as pd
test = pd.read_csv('C:/Users/valha/Documents/Classeur1.csv') 

In [ ]:
predicted_y = best_model.predict(test) 

In [ ]:
pip install tensorflow==2.5.2

In [ ]:
import pandas as pd
df = pd.read_csv('C:/Users/valha/Downloads/titanic.csv') 

In [ ]:
df = df.dropna()

In [ ]:
df.head()

In [ ]:
df.columns

In [ ]:
X = df.drop(columns = ['Survived'],axis=1)
y = df['Survived']

In [72]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [73]:
import pandas as pd
df = pd.read_excel('drive/My Drive/BNA/BNA 2022-MEAE-Données brutes.xlsx') 

In [74]:
df.head()

Ministere Q1.Maitrise_ENT  \
0  Ministère de l'Europe et des Affaires Etrangères     Plutôt bien   
1  Ministère de l'Europe et des Affaires Etrangères        Très mal   
2  Ministère de l'Europe et des Affaires Etrangères     Plutôt bien   
3  Ministère de l'Europe et des Affaires Etrangères       Très bien   
4  Ministère de l'Europe et des Affaires Etrangères     Plutôt bien   

                             Q2.Sedentaire_ou_nomade  \
0  Majoritairement sédentaire (lieu de travail fi...   
1  Majoritairement nomade (déplacements fréquents...   
2  Majoritairement sédentaire (lieu de travail fi...   
3  Majoritairement sédentaire (lieu de travail fi...   
4  Majoritairement nomade (déplacements fréquents...   

                          Q3.Frequence_teletravail  \
0  Très régulièrement (1 jour par semaine ou plus)   
1              Régulièrement (1 à 3 fois par mois)   
2                                           Jamais   
3                Rarement (de 1 à 11 jours par an)   
4  Très régulièrement (1 jour par semaine ou plus)   

                          Q4.Equipements_possedes Q5.equipement_prive_vs_pro  \
0                             Ordinateur portable                 Moins bien   
1  Ordinateur fixe;Ordinateur portable;Smartphone                 Moins bien   
2                                 Ordinateur fixe                 Moins bien   
3                  Ordinateur portable;Smartphone    Ni mieux, ni moins bien   
4                  Ordinateur portable;Smartphone    Ni mieux, ni moins bien   

        Q6.Utilisation_equipement_prive  \
0  Oui, parce qu'il est plus performant   
1  Oui, parce qu'il est plus performant   
2            Non, je ne le souhaite pas   
3            Non, je ne le souhaite pas   
4            Non, je ne le souhaite pas   

                     Q7.amelioration_Ordinateur_Fixe  \
0                                                NaN   
1  L’absence de bugs (dysfonctionnement du logici...   
2                               L’espace de stockage   
3                                                NaN   
4                                                NaN   

                 Q8.amelioration_Ordinateur_Portable Q9.amelioration_Tablette  \
0                               La taille de l’écran                      NaN   
1  La possibilité de travailler simultanément sur...                      NaN   
2                                                NaN                      NaN   
3          Les ports disponibles (USB, HDMI, VGA...)                      NaN   
4     L’encombrement (taille, poids de l’équipement)                      NaN   

   ... QS1_MEAE_genre QS2_MEAE_outils_de_travail_a_distance  \
0  ...       Un homme                                Itinéo   
1  ...      Une femme                        Itinéo;Smarteo   
2  ...       Un homme                                 Aucun   
3  ...      Une femme                        Itinéo;Smarteo   
4  ...       Un homme                        Itinéo;Smarteo   

                   QS3_MEAE_niveau_acces_equipements  \
0  Utilisateur (sans pouvoir installer des applic...   
1  Utilisateur (sans pouvoir installer des applic...   
2  Utilisateur (sans pouvoir installer des applic...   
3  Utilisateur (sans pouvoir installer des applic...   
4  Utilisateur (sans pouvoir installer des applic...   

                               QS4_MEAE_applications  \
0  Word;Excel;Outlook;Diplomatie;Diplonet;Viséo;F...   
1  Excel;Word;Diplonet;Portail Elise;Powerpoint;V...   
2  RMV-France Visas;Portail Elise;Sagha;Colimatic...   
3  Word;Diplonet;Excel;Portail Elise;Powerpoint;V...   
4  Word;Diplonet;Sagha;Excel;Portail Elise;Powerp...   

                            QS5_MEAE_informations QS6_MEAE_informations_bis  \
0       Toujours accessibles et rapides à trouver                En général   
1       Toujours accessibles et rapides à trouver                En général   
2  Toujours accessibles mais difficiles à trouver                En général   
3  Toujours accessib

In [75]:
df.columns

Index(['Ministere', 'Q1.Maitrise_ENT', 'Q2.Sedentaire_ou_nomade',
       'Q3.Frequence_teletravail', 'Q4.Equipements_possedes',
       'Q5.equipement_prive_vs_pro', 'Q6.Utilisation_equipement_prive',
       'Q7.amelioration_Ordinateur_Fixe',
       'Q8.amelioration_Ordinateur_Portable', 'Q9.amelioration_Tablette',
       'Q10.amelioration_smartphone', 'Q11.Satisfaction_equipement',
       'Q12.Qualification_equipement',
       'Q13.Equipement_utile_et_ecoresponsable',
       'Q14.Elements_ameliorer_reseau', 'Q15.Satisfaction_connectivite',
       'Q16.Amelioration_outils_et_app', 'Web_conf_Etat', 'Webinaire',
       'Audioconference_de_lEtat', 'Osmose', 'Resana', 'Tchap',
       'France_Transfert', 'Maia', 'RenoiRH', 'Chorus_DT', 'Vaas', 'Mentor',
       'Chorus', 'Q18.condition_securite', 'Q19.Satisfaction_outils_et_app',
       'Q20.souhait_formation', 'Q21.domaine_formation',
       'Q22.Formation_outils', 'Q23.Formation_outils_Autre',
       'Q24.format_formation', 'Q25.services_ac

In [76]:
df['Q11.Satisfaction_equipement'].unique()

array(['Plutôt satisfait', 'Plutôt pas satisfait', 'Très satisfait',
       'Pas du tout satisfait', nan], dtype=object)

In [77]:
df = df[['Q31.Tranche_age', 'Q34.categorie', 'Q11.Satisfaction_equipement', 'QS2_MEAE_outils_de_travail_a_distance']]
df = df.dropna()

In [78]:
df['Q11.Satisfaction_equipement']=df['Q11.Satisfaction_equipement'].replace('Plutôt satisfait', 1)
df['Q11.Satisfaction_equipement']=df['Q11.Satisfaction_equipement'].replace('Très satisfait', 1)
df['Q11.Satisfaction_equipement']=df['Q11.Satisfaction_equipement'].replace('Plutôt pas satisfait', 0)
df['Q11.Satisfaction_equipement']=df['Q11.Satisfaction_equipement'].replace('Pas du tout satisfait', 0)

In [ ]:
#histogramme
plt.gca().yaxis.set_major_formatter(PercentFormatter(1))
https://stackoverflow.com/questions/62974490/how-do-i-add-percent-values-on-top-of-histogram-bar-in-matplotlib

In [79]:
%pylab inline
#import pymysql
import pandas as pd
import seaborn as sns
import matplotlib.lines as mlines
from numpy.core.umath_tests import inner1d
from mpl_toolkits.mplot3d import Axes3D
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import confusion_matrix
import statsmodels.api as sm
from sklearn.svm import SVC
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.naive_bayes import GaussianNB
from xgboost import XGBClassifier
from sklearn.model_selection import GridSearchCV
from xgboost.sklearn import XGBClassifier
from sklearn.model_selection import KFold
import xgboost as xgb
from xgboost import plot_importance, to_graphviz
#import tensorflow as tf
#from keras.models import Sequential
#from keras.layers import Dropout, Dense
from sklearn import model_selection
from sklearn.utils import class_weight
from sklearn.metrics import classification_report
from sklearn.metrics import confusion_matrix
from sklearn.metrics import accuracy_score, precision_score, f1_score, recall_score, roc_auc_score   
#from minisom import MiniSom

Populating the interactive namespace from numpy and matplotlib


/usr/local/lib/python3.7/dist-packages/IPython/core/magics/pylab.py:161: UserWarning: pylab import has clobbered these variables: ['f']
`%matplotlib` prevents importing * from pylab and numpy
  "\n`%matplotlib` prevents importing * from pylab and numpy"


In [80]:
import re
df['Smarteo']=df['QS2_MEAE_outils_de_travail_a_distance'].str.contains('Smarteo', regex=True)

In [81]:
df['Smarteo'] = df['Smarteo'].replace({True: 'Oui', False: 'Non'})

In [82]:
y = df['Q11.Satisfaction_equipement']
X = df.drop(columns = ['Q11.Satisfaction_equipement','QS2_MEAE_outils_de_travail_a_distance'],axis=1)

In [83]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X,y, test_size=0.2, random_state=2)

In [84]:
pip install autokeras

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/


In [85]:
import numpy as np
import pandas as pd
import tensorflow as tf

import autokeras as ak

In [86]:
train_features = X_train
train_label = y_train
test_features = X_test
test_label = y_test

estimateur = ak.StructuredDataClassifier()

epochs=
estimateur.fit(x=train_features,
y=train_label,
validation_data=(test_features, test_label), epochs=epochs)

SyntaxError: ignored

In [ ]:
tensorboard --logdir logs/fit

In [87]:
best_model = estimateur.export_model()
best_model.summary()

Model: "model"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 input_1 (InputLayer)        [(None, 3)]               0         
                                                                 
 multi_category_encoding (Mu  (None, 3)                0         
 ltiCategoryEncoding)                                            
                                                                 
 normalization (Normalizatio  (None, 3)                7         
 n)                                                              
                                                                 
 dense (Dense)               (None, 32)                128       
                                                                 
 batch_normalization (BatchN  (None, 32)               128       
 ormalization)                                                   
                                                             

In [ ]:
test_features = test_features.astype('float')
test_features.dtypes

In [88]:
predicted_l = best_model.predict(X_train) 

In [89]:
X_train = X_train.assign(predictions_satisfaction = predicted_l)

In [90]:
X_train['predictions_satisfaction'].mean()

0.7490061521530151

In [91]:
#classification des commentaires selon trois modalités (neutres, positifs et négatifs) dans un dataframe
def f(df_polarity_desc1):
    if df_polarity_desc1['sentiment'] > 0:
        val = "positive"
    elif df_polarity_desc1['sentiment'] < 0:
        val = "negative"
    else :
        val = "neutre"
    return val

df_polarity_desc1.apply(f, axis=1)
df_polarity_desc1['polarite']=df_polarity_desc1.apply(f, axis=1)

NameError: ignored

In [92]:
#classe = 0
def f(X_train) :
  if X_train['predictions_satisfaction'] > 0.5 :
    classe = 1
  elif X_train['predictions_satisfaction'] <= 0.5 :
    classe = 0
  return classe

X_train.apply(f, axis=1)

X_train['classes']=X_train.apply(f, axis=1)

In [93]:
X_train['classes'].mean()

1.0

In [94]:
X_train['classes'].mean()

1.0

In [99]:
X_train= X_train.drop('predictions_satisfaction', axis=1)

In [102]:
#X_train= X_train.drop('predictions_satisfaction', axis=1)
X_train= X_train.drop('classes', axis=1)

In [95]:
dfr = []
x = range(50)

for n in x : 
  res = 'X' + str(n)
  dfr.append(res)

In [97]:
import numpy

In [96]:
res = []
for data in dfr :
  data = X.copy()
  data['Itinéo'] = np.ramdom.permutation(data['Itinéo'].values)
  predicted_y = best_model.predict(data)
  data = data.assign(predictions_satisfaction=predicted_y)
  result=data['predictions_satisfaction'].mean()
  res.append(result)

AttributeError: ignored

In [101]:
X_train.head()

Q31.Tranche_age Q34.categorie Smarteo  classes
2089  Entre 25 et 34 ans             A     Non        1
1975  Entre 35 et 49 ans             A     Oui        1
1186  Entre 25 et 34 ans             C     Non        1
1180  Entre 35 et 49 ans             C     Non        1
883   Entre 50 et 64 ans             A     Oui        1

In [103]:
Max = [0,0,0,0]

for data in dfr  :
    data = X_train.copy()
    #print(predicted_y)
    data['Smarteo'] = np.random.permutation(data['Smarteo'].values)
    #data['Smarteo'] = np.random.permutation(data['Smarteo'].values)
    predicted_y = best_model.predict(data)
    data = data.assign(predictions_satisfaction = predicted_y)
   
    # on fait la moyenne par catégorie
    dfgpby = data.groupby(['Q34.categorie'], as_index=False).mean()
    dfgpby.head()
    # on sauvegarde les noms des catégories et les moyennes associées
    categories = dfgpby['Q34.categorie'].values
    moyennes = dfgpby['predictions_satisfaction'].values
    print(categories)
    print(moyennes)
   
    pas_max = False
    # Boucle sur chaque catégorie
    for ind,val in enumerate(categories):
        # Si pour au moins une des catégories on n'est pas le Max,
        # alors on met passe le booléen à vrai pour l'indiquer
        if moyennes[ind] <= Max[ind]:
            pas_max = True
           
    # Si on a trouvé qu'on est max pour toutes les catégories,
    # alors on boucle et on sauvegarde
    if pas_max == False:
        for ind,val in enumerate(categories):
            Max[ind] = moyennes[ind]
        col = data['Smarteo'].values
        pred = data['predictions_satisfaction'].values
        data = data.assign(Itinéo = col)
        data = data.assign(predictions_satisfaction = pred)
        datadg = data.groupby(['Q34.categorie'])[['predictions_satisfaction', 'Smarteo']].agg(['mean', 'sum', 'count'])

['A' 'A+' 'B' 'C']
[0.7091485 0.70634   0.7067832 0.7998672]
['A' 'A+' 'B' 'C']
[0.70914495 0.7062559  0.7067991  0.80001086]
['A' 'A+' 'B' 'C']
[0.7091739  0.7066101  0.70684034 0.7999066 ]
['A' 'A+' 'B' 'C']
[0.70914495 0.706323   0.7067547  0.79996717]
['A' 'A+' 'B' 'C']
[0.70911044 0.7062868  0.7067868  0.7999914 ]
['A' 'A+' 'B' 'C']
[0.7092057 0.7065765 0.7067258 0.800049 ]
['A' 'A+' 'B' 'C']
[0.7092501  0.7064524  0.706869   0.80006814]
['A' 'A+' 'B' 'C']
[0.70910406 0.70621765 0.7068951  0.7998336 ]
['A' 'A+' 'B' 'C']
[0.70917034 0.7063001  0.70679116 0.79990935]
['A' 'A+' 'B' 'C']
[0.7092628  0.7063656  0.70681304 0.79997826]
['A' 'A+' 'B' 'C']
[0.7092184  0.70620316 0.70671815 0.8001296 ]
['A' 'A+' 'B' 'C']
[0.7092148  0.7063689  0.7067495  0.79991966]
['A' 'A+' 'B' 'C']
[0.7091739 0.7062723 0.7067658 0.7999464]
['A' 'A+' 'B' 'C']
[0.7091894  0.7065962  0.70676285 0.7998369 ]
['A' 'A+' 'B' 'C']
[0.7091132  0.70623285 0.70677817 0.79999155]
['A' 'A+' 'B' 'C']
[0.7091485 0.70654

In [105]:
 X_train.groupby(['Q34.categorie'])[['predictions_satisfaction', 'Smarteo']].agg(['mean', 'sum', 'count'])

KeyError: ignored

In [104]:
datadg

predictions_satisfaction                  
                                  mean         sum count
Q34.categorie                                           
A                             0.709231  349.650909   493
A+                            0.706620   97.513542   138
B                             0.706855  228.314316   323
C                             0.799970  599.977417   750

In [ ]:
print(predicted_l[:5])

In [ ]:
 tf.keras.utils.plot_model(best_model, show_shapes=True, expand_nested=True)

In [ ]:
pip install shap

In [ ]:
train_features.dtypes
train_features.astype('float')


In [ ]:
test_features.astype('float')

In [ ]:
# use Kernel SHAP to explain test set predictions
import shap
explainer = shap.KernelExplainer(best_model.predict, train_features)
shap_values = explainer.shap_values(test_features, nsamples=100)
shap.force_plot(explainer.expected_value[0], shap_values[0][0,:], test_features.iloc[0,:])

In [ ]:
# plot the SHAP values for the Setosa output of all instances
shap.force_plot(explainer.expected_value[0], shap_values[0], X_test, link="logit")

In [ ]:
import shap  
test = test_features.iloc[:100].flatten()
explainer = shap.DeepExplainer(best_model, test)

# calculate shap values. This is what we will plot.
#shap_values = explainer.shap_values(test_features)

In [ ]:
import lime

In [ ]:
columns = ['PassengerId', 'Pclass', 'Age', 'SibSp', 'Parch', 'Fare']

In [ ]:
# changed x to x_train
import lime.lime_tabular
explainer = lime.lime_tabular.LimeTabularExplainer(train_features, class_names=[0, 1], mode='classification')
# added top_labels=1
exp = explainer.explain_instance(test_features[2], best_model.predict, num_features=6, top_labels=1)

In [ ]:
def f(test_features):
    return best_model.predict([test_features[:,i] for i in range(test_features.shape[1])]).flatten()

In [ ]:
explainer = shap.KernelExplainer(f, test_features.iloc[:50,:])
shap_values = explainer.shap_values(test_features.iloc[299,:], nsamples=500)
shap.force_plot(explainer.expected_value, shap_values, X_display.iloc[299,:])

In [ ]:
best_model.predict(inputs)

In [ ]:
background = train_features.iloc[10, :]
background.dtypes
background.

In [ ]:
import shap
import numpy as np
# load your data here, e.g. X and y
# create and fit your model here

# load JS visualization code to notebook
shap.initjs()

# explain the model's predictions using SHAP
# (same syntax works for LightGBM, CatBoost, scikit-learn and spark models)
#background = X[np.random.choice(X.shape[0],100)]
background = train_features.iloc[10, :]
explainer = shap.DeepExplainer(best_model,background)
shap_values = explainer.shap_values(test_features)

# visualize the first prediction's explanation (use matplotlib=True to avoid Javascript)
shap.force_plot(explainer.expected_value, shap_values[0,:], X.iloc[0,:])

shap.summary_plot(shap_values, X, plot_type="bar")

In [ ]:
import shap

# we use the first 100 training examples as our background dataset to integrate over
explainer = shap.DeepExplainer(best_model, X_train[:100])

# explain the first 10 predictions
# explaining each prediction requires 2 * background dataset size runs
shap_values = explainer.shap_values(X_test[:10])

In [ ]:
print(tf.__version__)

In [ ]:
pip install tensorflow==2.3.0

In [ ]:
train_features.head()

In [ ]:
train_features = train_features.drop(columns = ['Lname', 'Name', 'Sex', 'Ticket', 'Embarked', 'Cabin'],axis=1)
test_features = test_features.drop(columns = ['Lname', 'Name', 'Sex', 'Ticket', 'Embarked', 'Cabin'],axis=1)

In [ ]:
pip install lime

In [ ]:
#train_features = train_features.as_matrix() 
feature_names = train_features.feature_names
train_pandas_df = train_features[feature_names].as_data_frame() 

#test_features = test_feature.as_matrix() 

In [ ]:
train_features.info()

In [ ]:
train_features = train_features.astype('float')
train_features.dtypes

PassengerId    float64
Pclass         float64
Age            float64
SibSp          float64
Parch          float64
Fare           float64
dtype: object

In [ ]:
train_features = train_features.astype('float')
train_features.dtypes

PassengerId    float64
Pclass         float64
Age            float64
SibSp          float64
Parch          float64
Fare           float64
dtype: object

In [ ]:
test_features = test_features.astype('float')
test_features.dtypes

PassengerId    float64
Pclass         float64
Age            float64
SibSp          float64
Parch          float64
Fare           float64
dtype: object

In [ ]:
test_features = test_features.drop(columns = ['Lname', 'Name', 'Sex', 'Ticket', 'Embarked', 'Cabin'],axis=1)

KeyError: "['Lname' 'Name' 'Sex' 'Ticket' 'Embarked' 'Cabin'] not found in axis"

In [ ]:
import shap
import numpy as np

# select a set of background examples to take an expectation over
#background = y_train[np.random.choice(y_train.shape[0], 100)]

# explain predictions of the model on three images
e = shap.DeepExplainer(best_model, train_features)
# ...or pass tensors directly
# e = shap.DeepExplainer((model.layers[0].input, model.layers[-1].output), background)
shap_values = e.shap_values(test_features[1:5])

Your TensorFlow version is newer than 2.4.0 and so graph support has been removed in eager mode and some static graphs may not be supported. See PR #1483 for discussion.


AttributeError: 'tuple' object has no attribute 'as_list'

In [ ]:
pip install torch

Note: you may need to restart the kernel to use updated packages.


In [ ]:
import torch
from torch.autograd import Variable
import shap
import numpy
import pandas

# It wants gradients enabled, and uses the training set
torch.set_grad_enabled(True)
e = shap.DeepExplainer(best_model, Variable( torch.from_numpy( train_features.to_numpy(dtype=np.float32) ) ) )

# Get the shap values from my test data (this explainer likes tensors)
shap_values = e.shap_values( Variable( torch.from_numpy(test_features.to_numpy(dtype=np.float32)) ) )

# Plots
#shap.force_plot(explainer.expected_value, shap_values, feature_names)
#shap.dependence_plot("b1_price_avg", shap_values, data, feature_names)
shap.summary_plot(shap_values, test_features.to_numpy(dtype=np.float32), feature_names)

Your TensorFlow version is newer than 2.4.0 and so graph support has been removed in eager mode and some static graphs may not be supported. See PR #1483 for discussion.


AttributeError: 'torch.Size' object has no attribute 'as_list'